language: php

php:
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - vendor/bin/phpspec run --config test/phpspec.yml

branches:
  except:
    - /^build-[0-9a-z\-]*/
